[OUT OF SCOPE] Add options to command signed-auth-url
creads/partners-sdk-php pull request #19
Opened 2018-11-30 09:48 UTC by abenevaut

**This PR is not attached to a Milestone - this is an optional feature "Dev only"**

I added three new option to overwrite the generated link.
Like this, we can generate links for different client and different environment of our production pipeline.

- `--client-id <param>`, works only if `--client-secret` is also set
- `--client-secret <param>`, works only if `--client-id` is also set
- `--api-base-uri <http://param.com/>`, could be used alone

```
bin/partners signed-auth-url Creads antoine@benevaut.fr --client-id test --client-secret test --api-base-uri http://test/
http://test/signed-auth//Q3JlYWRz/YW50b2luZUBiZW5ldmF1dC5mcg==//?expires=20181130T094541Z&signature=a886be05e66ef742129f43d83bde70ee07a05c3c915551fef48c6ddfd57b5a1f&accessKeyId=test

```

2018-11-30 09:55 UTC, abenevaut commented
Release `1.2.1`.

2018-12-05 11:01 UTC, AlexStef requested changes

2018-12-05 11:01 UTC, AlexStef commented on src/Console/Command/SignedAuthUrlCommand.php
> +        $api_base_uri = $input->getOption('api-base-uri');
@abenevaut camelCase maybe ?

2018-12-05 11:20 UTC, abenevaut commented on src/Console/Command/SignedAuthUrlCommand.php
> +        $api_base_uri = $input->getOption('api-base-uri');
With my all apologies, done.

2018-12-10 14:58 UTC, abenevaut commented
@AlexStef J'ai fait les modifications demandées

2018-12-10 15:55 UTC, AlexStef approved these changes

2018-12-13 09:46 UTC, pitpit approved these changes

2018-12-13 10:39 UTC, abenevaut commented
@AlexStef Ready pour merger, est ce que dans la foulé tu peux tagger 1.2.1 stp ?

2018-12-13 10:41 UTC, merged

2018-12-13 10:44 UTC, AlexStef commented
@abenevaut c'est fait