✨ Rendre obligatoire les tests Travis PHP7 sur le vendor partners-sdk-php
creads/partners-sdk-php pull request #20
Opened 2019-01-31 15:59 UTC by D1nker

FIX :
https://creads.atlassian.net/browse/CREADS-614

**Update du travis.yml**

+ Fin des tests PHP 5.5 & 5.6
+ Ajout des versions 7.1 & 7.2 + Nightly
+ Fail interdit pour la version 7.0
+ fail autorisé pour la version 7.1

2019-01-31 16:11 UTC, D1nker commented
@abenevaut Trop sûr de mon coup, sur le fait qu'il y ait 4 pipeline désormais 7.0 / 7.1 / 7.2 / Nightly ?
Doit-on garder la 7.0 ?

2019-02-07 10:58 UTC, abenevaut commented
@D1nker C'est tout à fait normal que plusieurs pipelines apparaissent, comme tu les as ajoutés ca prouve que ca fonctionne.

2019-02-07 11:12 UTC, abenevaut requested changes

2019-02-07 11:12 UTC, abenevaut commented on .travis.yml
> -  - 5.5
We will keep version 5.x:

```
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
```

2019-02-07 11:12 UTC, abenevaut commented on .travis.yml
> +    - php: 7.1
You say here that php 7.1 is allowed to fail. We are looking for the opposite, here all our developments must pass on PHP7.1 at least

We will also put versions 5.5, 5.6, 7.0 and nightly as allowed to fail.
The interest here is that we test on the public pipeline (it's a public repo) PHP versions that our customers could have BUT that we no longer want to support (http://php.net/supported -versions.php to see PHP versions that are no longer maintained) and if tests ever pass they can use the package, charge them to see that they are on an outdated system.
On the other hand, for the nightly, we want to anticipate the future update of PHP (nightly -> nightly build of the last version of PHP (potentially php3 if I say no stupidity)), so we are in the case we want.

```
matrix:
  allow_failures:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: nightly
```

2019-02-07 14:09 UTC, abenevaut approved these changes

2019-02-07 14:09 UTC, abenevaut commented
@AlexStef ready to merge

2019-02-07 14:13 UTC, AlexStef commented
@abenevaut shouldn't we reduce the scope of tested  PHP versions ? Maybe 5.5 and 5.6 and not different enought to justify multiplying the pipelines, it adds workload on Travis' back

2019-02-08 14:10 UTC, AlexStef commented
🤷‍♂️

2019-02-08 14:48 UTC, abenevaut commented
There is some difference between PHP 5.5 and 5.6 (new or deprecated feature) but not all are applicable on this project (http://php.net/manual/en/migration56.php).

Here we do not offer the support on PHP 5.5 and 5.6 (and PHP 7.0), so we are able to choose which version of PHP are ran on pipelines. As it is only for indication purposes, yes we can reduce the scope. So.. We can made it! (*private joke ;)

Now should we do it?  As you said, it's probably a good idea not to overload Travis's pipelines with this project and unsupported PHP version. 
I think it still has to be communicated to the entire team to know if a communication needs to be done, then we will be able to do it (maybe another US ?).

2019-02-08 14:49 UTC, AlexStef commented
100% agree, maybe @pitpit could give us some insights about this ?

2019-02-08 17:05 UTC, pitpit commented
I vote to keep testing all PHP versions 👍

2019-02-08 17:06 UTC, merged